name: Update bientot.json

permissions:
  contents: write

on:
  workflow_dispatch:         # Permet de lancer manuellement

jobs:
  update-films:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Exécuter le script
        run: python update_films.py

      - name: Commit et push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add bientot.json
          git diff --cached --quiet || git commit -m "🔄 Mise à jour automatique de bientot.json"
          git pull --rebase origin main
          git push origin main

